###
GET http://localhost:3001/api/cars/

###
GET http://localhost:3001/api/cars/search/1

###
POST http://localhost:3001/api/cars/post
Content-Type: application/json

{
    "id": "6",
    "title": "Tesla Roadster",
    "image": "https://news7h.com/wp-content/uploads/2021/10/1teslaroadster.jpg",
    "price": 130000,
    "numberplates": "YYY555"
}

###
DELETE http://localhost:3001/api/cars/3