###
GET http://localhost:3001/api/cars/

###
GET http://localhost:3001/api/cars/search/1

###
POST http://localhost:3001/api/cars
Content-Type: application/json

{
    "title": "Tesla",
    "image": "https://news7h.com/wp-content/uploads/2021/10/1teslaroadster.jpg",
    "price": "130000",
    "numberplates": "YYY555"
}

###
DELETE http://localhost:3001/api/cars/3